const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});
$$(".reveal").forEach(el=>io.observe(el));
const counters=$$(".stats strong"); let counted=false;
const co=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)&&!counted){counted=true;counters.forEach(el=>{const target=+el.dataset.count;let n=0;const step=Math.max(1,Math.ceil(target/20));const t=setInterval(()=>{n=Math.min(target,n+step);el.textContent=n;if(n>=target)clearInterval(t)},45)})}}, {threshold:.5});
if($(".stats"))co.observe($(".stats"));
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("dark",document.body.classList.contains("dark"))};
if(localStorage.getItem("dark")==="true")document.body.classList.add("dark");
let english=false;
$("#langBtn").onclick=()=>{english=!english;document.documentElement.lang=english?"en":"th";$("#langBtn").textContent=english?"TH":"EN";
$$("[data-th]").forEach(el=>el.textContent=english?el.dataset.en:el.dataset.th);
};
window.addEventListener("scroll",()=>document.querySelector(".nav").style.boxShadow=scrollY>20?"0 8px 30px rgba(0,0,0,.05)":"none");